// g2p_en_lexicon.dart — bundled high-frequency English exception lexicon.
//
// A modest const map of common English words → espeak-ng-style IPA (what
// Kokoro-82M was trained on). The rule-based LTS engine ([g2p_en.dart]) is the
// generalising fallback; this lexicon fixes the many high-frequency words whose
// pronunciation the LTS rules cannot derive (irregular vowels, silent letters,
// function-word reductions, r-colouring). Entries are authored from general
// English pronunciation knowledge in espeak's transcription conventions
// (primary stress ˈ, secondary ˌ, length ː, ɹ for /r/, ɡ script-g, diphthongs
// eɪ/aɪ/aʊ/oʊ/ɔɪ, reduced ə/ɪ/ɐ/ɚ). Keys are lowercase.
//
// Kept intentionally small (well under the source budget). Anything not here is
// handled by the LTS rules.
const Map<String, String> kEnLexicon = {
  // Function words / determiners / pronouns.
  'the': 'ðə',
  'a': 'ɐ',
  'an': 'ɐn',
  'and': 'ænd',
  'or': 'ɔː',
  'but': 'bˈʌt',
  'of': 'ʌv',
  'to': 'tə',
  'in': 'ɪn',
  'is': 'ɪz',
  'it': 'ɪt',
  'you': 'juː',
  'that': 'ðæt',
  'he': 'hiː',
  'she': 'ʃiː',
  'we': 'wiː',
  'they': 'ðeɪ',
  'was': 'wɒz',
  'for': 'fɔː',
  'on': 'ɒn',
  'are': 'ɑː',
  'with': 'wɪð',
  'as': 'æz',
  'his': 'hɪz',
  'i': 'aɪ',
  'at': 'æt',
  'be': 'biː',
  'this': 'ðɪs',
  'have': 'hæv',
  'from': 'fɹɒm',
  'not': 'nˌɒt',
  'by': 'baɪ',
  'word': 'wˈɜːd',
  'what': 'wˈɒt',
  'were': 'wɜː',
  'when': 'wˈɛn',
  'your': 'jɔː',
  'can': 'kæn',
  'said': 'sˈɛd',
  'there': 'ðˈɛə',
  'use': 'jˈuːz',
  'each': 'ˈiːtʃ',
  'which': 'wˈɪtʃ',
  'do': 'dˈuː',
  'how': 'hˈaʊ',
  'their': 'ðˈɛə',
  'will': 'wɪl',
  'other': 'ˈʌðɚ',
  'about': 'ɐbˈaʊt',
  'out': 'ˈaʊt',
  'many': 'mˈɛni',
  'then': 'ðˈɛn',
  'them': 'ðˈɛm',
  'these': 'ðiːz',
  'so': 'sˈoʊ',
  'some': 'sˈʌm',
  'her': 'hɜː',
  'would': 'wˈʊd',
  'make': 'mˈeɪk',
  'like': 'lˈaɪk',
  'him': 'hɪm',
  'into': 'ˈɪntʊ',
  'time': 'tˈaɪm',
  'two': 'tˈuː',
  'more': 'mˈɔː',
  'go': 'ɡˈoʊ',
  'no': 'nˈoʊ',
  'way': 'wˈeɪ',
  'could': 'kˈʊd',
  'my': 'mˈaɪ',
  'than': 'ðæn',
  'first': 'fˈɜːst',
  'been': 'bˈiːn',
  'call': 'kˈɔːl',
  'who': 'hˈuː',
  'now': 'nˈaʊ',
  'people': 'pˈiːpəl',
  'down': 'dˈaʊn',
  'day': 'dˈeɪ',
  'did': 'dˈɪd',
  'get': 'ɡˈɛt',
  'come': 'kˈʌm',
  'made': 'mˈeɪd',
  'may': 'mˈeɪ',
  'part': 'pˈɑːt',
  'over': 'ˈoʊvɚ',
  'new': 'nˈuː',
  'sound': 'sˈaʊnd',
  'take': 'tˈeɪk',
  'only': 'ˈoʊnli',
  'little': 'lˈɪtəl',
  'work': 'wˈɜːk',
  'know': 'nˈoʊ',
  'place': 'plˈeɪs',
  'year': 'jˈɪɹ',
  'live': 'lˈɪv',
  'me': 'mˈiː',
  'back': 'bˈæk',
  'give': 'ɡˈɪv',
  'most': 'mˈoʊst',
  'very': 'vˈɛɹi',
  'good': 'ɡˈʊd',
  'through': 'θɹˈuː',
  'just': 'dʒˈʌst',
  'because': 'bɪkˈʌz',
  'name': 'nˈeɪm',
  'great': 'ɡɹˈeɪt',
  'where': 'wˈɛə',
  'much': 'mˈʌtʃ',
  'before': 'bɪfˈɔː',
  'right': 'ɹˈaɪt',
  'too': 'tˈuː',
  'any': 'ˈɛni',
  'same': 'sˈeɪm',
  'tell': 'tˈɛl',
  'boy': 'bˈɔɪ',
  'follow': 'fˈɒloʊ',
  'came': 'kˈeɪm',
  'want': 'wˈɒnt',
  'show': 'ʃˈoʊ',
  'also': 'ˈɔːlsoʊ',
  'around': 'ɐɹˈaʊnd',
  'form': 'fˈɔːm',
  'three': 'θɹˈiː',
  'small': 'smˈɔːl',
  'set': 'sˈɛt',
  'put': 'pˈʊt',
  'end': 'ˈɛnd',
  'why': 'wˈaɪ',
  'again': 'ɐɡˈɛn',
  'turn': 'tˈɜːn',
  'here': 'hˈɪɹ',
  'off': 'ˈɒf',
  'went': 'wˈɛnt',
  'old': 'ˈoʊld',
  'number': 'nˈʌmbɚ',
  'water': 'wˈɔːtɚ',
  'one': 'wˈʌn',
  'all': 'ˈɔːl',
  'world': 'wˈɜːld',
  'hello': 'hɐlˈoʊ',
  'colonel': 'kˈɜːnəl',
  'women': 'wˈɪmɪn',
  'wednesday': 'wˈɛnzdeɪ',
  'once': 'wˈʌns',
  'love': 'lˈʌv',
  'music': 'mjˈuːzɪk',
  'friend': 'fɹˈɛnd',
  'says': 'sˈɛz',
  'answer': 'ˈɑːnsɚ',
  'busy': 'bˈɪzi',
  'build': 'bˈɪld',
};
