// g2p_de_lexicon.dart — bundled high-frequency German exception lexicon.
//
// A modest const map of common German words → espeak-ng-style IPA. The German
// LTS engine ([g2p_de.dart]) generalises but emits no primary-stress mark and
// approximates /r/; this lexicon supplies stressed, espeak-faithful forms for
// frequent words (primary stress ˈ, length ː, ɐ for vocalised -er, ɾ/ʁ for /r/,
// diphthongs aɪ̯/aʊ̯/ɔʏ̯). Keys are lowercase (umlaut-aware).
//
// Kept intentionally small; anything absent falls through to the LTS rules.
const Map<String, String> kDeLexicon = {
  // Pronouns / function words.
  'ich': 'ˈɪç',
  'du': 'dˈuː',
  'er': 'ˈɛɾ',
  'sie': 'zˈiː',
  'es': 'ˈɛs',
  'wir': 'vˈiːɾ',
  'ihr': 'ˈiːɾ',
  'und': 'ˈʊnt',
  'oder': 'ˈoːdɐ',
  'aber': 'ˈɑːbɐ',
  'nicht': 'nˈɪçt',
  'ja': 'jˈɑː',
  'nein': 'nˈaɪ̯n',
  'ein': 'ˈaɪ̯n',
  'eine': 'ˈaɪ̯nə',
  'der': 'dˈeːɐ',
  'die': 'dˈiː',
  'das': 'dˈas',
  'den': 'dˈeːn',
  'dem': 'dˈeːm',
  'mit': 'mˈɪt',
  'auf': 'ˈaʊ̯f',
  'für': 'fˈyːɐ',
  'von': 'fˈɔn',
  'zu': 'tsˈuː',
  'im': 'ˈɪm',
  'ist': 'ˈɪst',
  'sind': 'zˈɪnt',
  'war': 'vˈɑː',
  'haben': 'hˈɑːbən',
  'hat': 'hˈat',
  'sein': 'zˈaɪ̯n',
  'werden': 'vˈɛɾdən',
  'wird': 'vˈɪɾt',
  'kann': 'kˈan',
  'muss': 'mˈʊs',
  'soll': 'zˈɔl',
  'mein': 'mˈaɪ̯n',
  'dein': 'dˈaɪ̯n',
  // Greetings / common nouns.
  'hallo': 'hˈaloː',
  'welt': 'vˈɛlt',
  'gut': 'ɡˈuːt',
  'morgen': 'mˈɔɾɡən',
  'abend': 'ˈɑːbənt',
  'nacht': 'nˈaxt',
  'danke': 'dˈaŋkə',
  'bitte': 'bˈɪtə',
  'schule': 'ʃˈuːlə',
  'sprechen': 'ʃpɾˈɛçən',
  'deutsch': 'dˈɔʏ̯tʃ',
  'kind': 'kˈɪnt',
  'kinder': 'kˈɪndɐ',
  'haus': 'hˈaʊ̯s',
  'mann': 'mˈan',
  'frau': 'fɾˈaʊ̯',
  'zeit': 'tsˈaɪ̯t',
  'jahr': 'jˈɑː',
  'tag': 'tˈɑːk',
  'wasser': 'vˈasɐ',
  'musik': 'muzˈiːk',
  'liebe': 'lˈiːbə',
  'freund': 'fɾˈɔʏ̯nt',
  'wie': 'vˈiː',
  'was': 'vˈas',
  'wer': 'vˈeːɐ',
  'wo': 'vˈoː',
  'wann': 'vˈan',
  'warum': 'vaɾˈʊm',
  'heute': 'hˈɔʏ̯tə',
  'immer': 'ˈɪmɐ',
  'sehr': 'zˈeːɐ',
  'schön': 'ʃˈøːn',
  'groß': 'ɡɾˈoːs',
  'klein': 'klˈaɪ̯n',
};
