// GENERATED by ../../sync_glint.sh — do not edit.
// Forwarder: podspecs cannot reference sources outside their dir, so this
// relatively includes the shared glint source. See ../glint_vorbis.podspec.
#include "../../src/aac_coder.cpp"
